apiVersion: v1
kind: Pod
metadata:
  name: busy
spec:
  containers:
  - image: busybox
    name: busybox
    command: ['sh', '-c', 'while true; do echo "Running..."; sleep 1h; done']
    securityContext:
      capabilities:
        drop:
        - ALL
        add:
        - SYSLOG
